wandb_version: 1

weights:
  desc: null
  value: yolov7.pt
cfg:
  desc: null
  value: ''
data:
  desc: null
  value: data/real_world.yaml
hyp:
  desc: null
  value:
    lr0: 0.001
    lrf: 0.001
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    cls: 0.75
    cls_pw: 1.0
    obj: 1.5
    obj_pw: 1.0
    iou_t: 0.2
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.05
    copy_paste: 0.0
    paste_in: 0.05
    loss_ota: 1
    path: ../data/real_world
    train: images/Real_world_training
    val: images/Real_world_training
    test: images/Real_world_training
    label: images/Real_world_training
    nc: 2
    names:
    - AIRPLANE
    - DRONE
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 14
img_size:
  desc: null
  value:
  - 640
  - 640
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
evolve:
  desc: null
  value: false
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: '0'
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
adam:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
workers:
  desc: null
  value: 0
project:
  desc: null
  value: runs/pgt/train-pgt-yolov7
entity:
  desc: null
  value: null
name:
  desc: null
  value: pgt
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
linear_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
save_period:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
freeze:
  desc: null
  value:
  - 0
v5_metric:
  desc: null
  value: false
loss_metric:
  desc: null
  value: CIoU
conf_thres:
  desc: null
  value: 0.5
iou_thres:
  desc: null
  value: 0.65
agnostic_nms:
  desc: null
  value: false
classes:
  desc: null
  value: null
pgt_lr:
  desc: null
  value: 0.0
out_num_attrs:
  desc: null
  value:
  - 1
loss_attr:
  desc: null
  value: false
pgt_lr_decay:
  desc: null
  value: 0.75
pgt_lr_decay_step:
  desc: null
  value: 20
no_trace:
  desc: null
  value: true
save_dir:
  desc: null
  value: runs\pgt\train-pgt-yolov7\pgt40
seed:
  desc: null
  value: 3974326285330947842
world_size:
  desc: null
  value: 1
global_rank:
  desc: null
  value: -1
total_batch_size:
  desc: null
  value: 14
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705607201.4579
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 13
      - 16
      - 19
      - 23
      4: 3.11.7
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
opt:
  desc: null
  value:
    weights: yolov7.pt
    cfg: ''
    data: data/real_world.yaml
    hyp:
      lr0: 0.001
      lrf: 0.001
      momentum: 0.937
      weight_decay: 0.0005
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      warmup_bias_lr: 0.1
      box: 0.05
      cls: 0.75
      cls_pw: 1.0
      obj: 1.5
      obj_pw: 1.0
      iou_t: 0.2
      anchor_t: 4.0
      fl_gamma: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      degrees: 0.0
      translate: 0.1
      scale: 0.5
      shear: 0.0
      perspective: 0.0
      flipud: 0.0
      fliplr: 0.5
      mosaic: 1.0
      mixup: 0.05
      copy_paste: 0.0
      paste_in: 0.05
      loss_ota: 1
      path: ../data/real_world
      train: images/Real_world_training
      val: images/Real_world_training
      test: images/Real_world_training
      label: images/Real_world_training
      nc: 2
      names:
      - AIRPLANE
      - DRONE
    epochs: 5
    batch_size: 14
    img_size:
    - 640
    - 640
    rect: false
    resume: false
    nosave: false
    notest: false
    noautoanchor: false
    evolve: false
    bucket: ''
    cache_images: false
    image_weights: false
    device: '0'
    multi_scale: false
    single_cls: false
    adam: false
    sync_bn: false
    local_rank: -1
    workers: 0
    project: runs/pgt/train-pgt-yolov7
    entity: null
    name: pgt
    exist_ok: false
    quad: false
    linear_lr: false
    label_smoothing: 0.0
    upload_dataset: false
    bbox_interval: -1
    save_period: -1
    artifact_alias: latest
    freeze:
    - 0
    v5_metric: false
    loss_metric: CIoU
    conf_thres: 0.5
    iou_thres: 0.65
    agnostic_nms: false
    classes: null
    pgt_lr: 0.0
    out_num_attrs:
    - 1
    loss_attr: false
    pgt_lr_decay: 0.75
    pgt_lr_decay_step: 20
    no_trace: true
    save_dir: runs\pgt\train-pgt-yolov7\pgt40
    seed: 3974326285330947842
    world_size: 1
    global_rank: -1
    total_batch_size: 14
data_dict:
  desc: null
  value:
    path: ../data/real_world
    train: images/Real_world_training
    val: images/Real_world_training
    test: images/Real_world_training
    label: images/Real_world_training
    nc: 2
    names:
    - AIRPLANE
    - DRONE
