weights: yolov7.pt
cfg: ''
data: data/real_world.yaml
hyp: data/hyp.real_world.yaml
epochs: 20
batch_size: 14
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 1
project: runs/pgt/train-pgt-yolov7
entity: null
name: pgt
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
loss_metric: CIoU
conf_thres: 0.5
iou_thres: 0.65
agnostic_nms: false
classes: null
pgt_lr: 0.7
out_num_attrs:
- 1
loss_attr: false
pgt_lr_decay: 0.75
pgt_lr_decay_step: 20
no_trace: true
save_dir: runs\pgt\train-pgt-yolov7\pgt16
seed: 97906947763170166
world_size: 1
global_rank: -1
total_batch_size: 14
